export const BANK_OPTIONS = [
  { value: 'absa', label: 'Absa Bank Kenya PLC', bankCode: '03', swiftCode: 'BARCKENX' },
  { value: 'access', label: 'Access Bank (Kenya) PLC', bankCode: '26', swiftCode: 'ABNGKENA' },
  { value: 'abc', label: 'African Banking Corporation (ABC Bank) Limited', bankCode: '35', swiftCode: 'ABCLKENA' },
  { value: 'boa', label: 'Bank of Africa Kenya Limited', bankCode: '19', swiftCode: 'AFRIKENX' },
  { value: 'bank_of_baroda', label: 'Bank of Baroda (Kenya) Limited', bankCode: '04', swiftCode: 'BARBKENA' },
  { value: 'bank_of_india', label: 'Bank of India', bankCode: '05', swiftCode: 'BKIDKENA' },
  { value: 'citibank', label: 'Citibank N.A. Kenya', bankCode: '16', swiftCode: 'CITIKENA' },
  { value: 'cib', label: 'Commercial International Bank (CIB) Kenya Limited', bankCode: '76', swiftCode: 'CIBKKENA' },
  { value: 'consolidated', label: 'Consolidated Bank of Kenya Limited', bankCode: '23', swiftCode: 'CONKKENA' },
  { value: 'cooperative', label: 'Co-operative Bank of Kenya Limited', bankCode: '11', swiftCode: 'KCOOKENA' },
  { value: 'credit', label: 'Credit Bank PLC', bankCode: '25', swiftCode: 'CRBTKENA' },
  { value: 'development', label: 'Development Bank of Kenya Limited', bankCode: '20', swiftCode: 'DEVKKENA' },
  { value: 'dtb', label: 'Diamond Trust Bank Kenya Limited', bankCode: '63', swiftCode: 'DTKEKENA' },
  { value: 'dib', label: 'DIB Bank Kenya Limited', bankCode: '78', swiftCode: 'DUIBKENA' },
  { value: 'ecobank', label: 'Ecobank Kenya Limited', bankCode: '43', swiftCode: 'ECOCKENA' },
  { value: 'equity', label: 'Equity Bank Kenya Limited', bankCode: '68', swiftCode: 'EQBLKENX' },
  { value: 'family', label: 'Family Bank Limited', bankCode: '70', swiftCode: 'FABLKENA' },
  { value: 'first_community', label: 'First Community Bank Limited', bankCode: '74', swiftCode: 'IFCBKENA' },
  { value: 'guardian', label: 'Guardian Bank Limited', bankCode: '55', swiftCode: 'GBOKKENA' },
  { value: 'gulf_african', label: 'Gulf African Bank Limited', bankCode: '72', swiftCode: 'GAFRKENA' },
  { value: 'gtbank', label: 'Guaranty Trust Bank (Kenya) Limited', bankCode: '53', swiftCode: 'GTBIKENA' },
  { value: 'habib', label: 'Habib Bank AG Zurich', bankCode: '17', swiftCode: 'HBZUKENA' },
  { value: 'hf_group', label: 'Housing Finance Company of Kenya (HF Group)', bankCode: '61', swiftCode: 'HFCOKENA' },
  { value: 'iandm', label: 'I&M Bank Limited', bankCode: '57', swiftCode: 'IMBLKENA' },
  { value: 'kcb', label: 'KCB Bank Kenya Limited', bankCode: '01', swiftCode: 'KCBLKENX' },
  { value: 'kingdom', label: 'Kingdom Bank Limited', bankCode: '68', swiftCode: 'CIFIKENA' },
  { value: 'mayfair', label: 'Mayfair Bank Limited', bankCode: '76', swiftCode: 'MYBKKENA' },
  { value: 'middle_east', label: 'Middle East Bank (K) Limited', bankCode: '18', swiftCode: 'MIEKKENA' },
  { value: 'm_oriental', label: 'M-Oriental Bank Limited', bankCode: '14', swiftCode: 'MORBKENA' },
  { value: 'national', label: 'National Bank of Kenya Limited', bankCode: '12', swiftCode: 'NBKEKENX' },
  { value: 'ncba', label: 'NCBA Bank Kenya PLC', bankCode: '07', swiftCode: 'CBAFKENX' },
  { value: 'paramount', label: 'Paramount Bank Limited', bankCode: '50', swiftCode: 'PAUTKENA' },
  { value: 'premier', label: 'Premier Bank Kenya Limited', bankCode: '79', swiftCode: 'PRMRKENA' },
  { value: 'prime', label: 'Prime Bank Limited', bankCode: '10', swiftCode: 'PRIEKENX' },
  { value: 'sbm', label: 'SBM Bank (Kenya) Limited', bankCode: '60', swiftCode: 'SBMKKENA' },
  { value: 'sidian', label: 'Sidian Bank Limited', bankCode: '66', swiftCode: 'SIDNKENA' },
  { value: 'standard_chartered', label: 'Standard Chartered Bank Kenya Limited', bankCode: '02', swiftCode: 'SCBLKENX' },
  { value: 'stanbic', label: 'Stanbic Bank Kenya Limited', bankCode: '31', swiftCode: 'SBICKENX' },
  { value: 'uba', label: 'UBA Kenya Bank Limited', bankCode: '37', swiftCode: 'UNAFKENA' },
  { value: 'victoria', label: 'Victoria Commercial Bank PLC', bankCode: '54', swiftCode: 'VICBKENA' },
  { value: 'other', label: 'Other', bankCode: '', swiftCode: '' },
];

export default BANK_OPTIONS;
